---
- hosts: all
  remote_user: ubuntu

  vars:
    service: valheim
    sniff_port: 2456

  vars_prompt:
    - name: "valheim_server_name"
      prompt: "What is the server name ?"
      private: no
    - name: "valheim_world_name"
      prompt: "What is the world name ?"
      private: no
    - name: "valheim_server_password"
      prompt: "What is the server password ? (at least 5 characters are required !)"
      private: no

  roles:
    - supervised
    - steam
    - valheim
