---
- name: Setup folder
  ansible.builtin.file:
    path: /home/steam/valheim
    state: directory
    mode: '0755'

- name: Install game
  ansible.builtin.command:
    cmd: /usr/games/steamcmd +login anonymous +force_install_dir /home/steam/valheim +app_update {{ valheim_app_id }} validate +exit
    creates: /home/steam/valheim/valheim_server.x86_64

- name: Upload world
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/steam/.config/unity3d/IronGate/Valheim/worlds/
  with_fileglob:
    - "{{ playbook_dir }}/{{valheim_world_name}}.*"
  when: worldfile.stat.exists
  notify: supervisord restart service
