---
- name: supervisord reload
  become: true
  shell: supervisorctl reload

- name: supervisord restart service
  become: true
  community.general.supervisorctl:
    name: "{{ service }}"
    state: restarted
